"""
Neural Network Training for Element Identification

This script:
1. Generates synthetic spectra via SyntheticLIBSDataset (Sample_bootstrap.py)
2. Loads multi-weight spectra from element_weights/multi_weights.h5
   (generated by weight_generator.py: 100 TE/NE combos x 77 elements = 7700 rows)
3. Performs matrix multiplication: spectra @ weights.T  -> (n_samples, 7700)
4. Reduces 7700 features to 77 via a trainable projection matrix (optimized during training)
5. Feeds the 77 projected features into a FC hidden layer
6. Predicts element presence (0-1) for all 77 elements

Architecture:
    spectra @ weight_spectra.T -> (n, 7700) @ W_proj -> (n, 77) -> Hidden -> Output (77)
    W_proj is randomly initialized and learned jointly with the NN weights.

Prerequisite:
    Run weight_generator.py first to generate element_weights/multi_weights.h5

Uses PyTorch if available, otherwise falls back to optimized NumPy.
"""

import numpy as np
import h5py
import os
import sys
import pickle
import Sample_bootstrap as sample_bootstrap

# Try to import PyTorch
try:
    import torch  # type: ignore[import-not-found]
    import torch.nn as nn  # type: ignore[import-not-found]
    import torch.optim as optim  # type: ignore[import-not-found]
    from torch.utils.data import DataLoader, TensorDataset  # type: ignore[import-not-found]
    USE_TORCH = True
    print("Using PyTorch backend")
except ImportError:
    USE_TORCH = False
    print("PyTorch not available, using NumPy backend")

# ============================================================================
# Configuration
# ============================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MULTI_WEIGHTS_PATH = os.path.join(SCRIPT_DIR, 'element_weights', 'multi_weights_vacuum.h5')

# Neural network parameters
HIDDEN_LAYER_SIZE = 256
LEARNING_RATE = 0.01
EPOCHS = 1000
BATCH_SIZE = 8
TEST_SPLIT = 0.2
RANDOM_SEED = 17

np.random.seed(RANDOM_SEED)
if USE_TORCH:
    torch.manual_seed(RANDOM_SEED)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


# ============================================================================
# Data Loading and Preparation
# ============================================================================

def load_multi_weights():
    """
    Load multi-weight spectra from element_weights/multi_weights_vacuum.h5
    (generated by weight_generator.py).
    """
    if not os.path.exists(MULTI_WEIGHTS_PATH):
        print(f"\nERROR: Multi-weight file not found: {MULTI_WEIGHTS_PATH}")
        print("Please run weight_generator.py first to generate the weight spectra.")
        sys.exit(1)
    
    print(f"Loading multi-weight spectra from: {MULTI_WEIGHTS_PATH}")
    with h5py.File(MULTI_WEIGHTS_PATH, 'r') as f:
        weight_matrix = f['weight_matrix'][:]
        unique_elements = [e.decode('utf-8') for e in f['unique_elements'][:]]
        element_labels = [e.decode('utf-8') for e in f['element_labels'][:]]
        te_values = f['te_values'][:]
        ne_values = f['ne_values'][:]
    
    n_elements = len(unique_elements)
    n_combos = len(te_values) * len(ne_values)
    
    print(f"  Weight matrix: {weight_matrix.shape}")
    print(f"  Elements: {n_elements}")
    print(f"  TE/NE combinations: {n_combos}")
    print(f"  Total weight spectra: {n_combos} x {n_elements} = {weight_matrix.shape[0]}")
    
    return weight_matrix, unique_elements


def load_synthetic_data_from_dataloader(batch_size=64):
    """
    Generate synthetic spectra/targets using SyntheticLIBSDataset and DataLoader.
    """
    print("\nGenerating synthetic data via SyntheticLIBSDataset...")
    synthetic_dataset = sample_bootstrap.SyntheticLIBSDataset(
        sample_types=sample_bootstrap.SAMPLE_TYPES,
        wavelength=sample_bootstrap.wavelength,
        db_path=sample_bootstrap.DATABASE_PATH,
        te_range=(sample_bootstrap.TE_MIN, sample_bootstrap.TE_MAX),
        ne_range=(sample_bootstrap.NE_MIN, sample_bootstrap.NE_MAX),
        verbose=False
    )

    if len(synthetic_dataset) == 0:
        print("\nERROR: Synthetic dataset is empty. Check SAMPLE_TYPES configuration.")
        sys.exit(1)

    non_element_cols = {'Te', 'Ne', 'sample_type_id', 'sample_type_name', 'unique_id'}
    synth_elements = [
        col for col in synthetic_dataset.sample_table.columns
        if col not in non_element_cols
    ]

    concentrations_np = synthetic_dataset.sample_table[synth_elements].to_numpy(dtype=np.float32)
    spectra_np = synthetic_dataset.spectra.astype(np.float32)

    if USE_TORCH:
        data_loader = DataLoader(
            TensorDataset(torch.FloatTensor(spectra_np), torch.FloatTensor(concentrations_np)),
            batch_size=batch_size,
            shuffle=False,
            num_workers=12
        )

        spectra_batches = []
        concentration_batches = []
        for spectra_batch, concentrations_batch in data_loader:
            spectra_batches.append(spectra_batch.numpy())
            concentration_batches.append(concentrations_batch.numpy())

        spectra = np.vstack(spectra_batches)
        concentrations = np.vstack(concentration_batches)
    else:
        spectra = spectra_np
        concentrations = concentrations_np

    print(f"  Spectra: {spectra.shape}")
    print(f"  Concentrations: {concentrations.shape}")
    print(f"  Elements ({len(synth_elements)}): {synth_elements}")

    return spectra, concentrations, synth_elements


def prepare_features(synthetic_spectra, weight_matrix):
    """Apply matrix multiplication: spectra @ weights.T"""
    print(f"\nComputing feature matrix via matrix multiplication...")
    print(f"  synthetic_spectra: {synthetic_spectra.shape}")
    print(f"  weight_matrix.T: {weight_matrix.T.shape}")
    
    features = synthetic_spectra @ weight_matrix.T
    features = np.nan_to_num(features, nan=0.0, posinf=0.0, neginf=0.0)
    
    print(f"  Result features: {features.shape}")
    return features


def prepare_targets(concentrations, synth_elements, weight_elements, threshold=0.0):
    """
    Create target matrix for all weight elements.
    Output values: 0 = element not present, 1 = element present
    """
    n_samples = concentrations.shape[0]
    n_weight_elements = len(weight_elements)
    
    element_to_idx = {elem: idx for idx, elem in enumerate(weight_elements)}
    targets = np.zeros((n_samples, n_weight_elements), dtype=np.float32)
    
    print(f"\nMapping synthetic elements to weight element indices:")
    for i, elem in enumerate(synth_elements):
        if elem in element_to_idx:
            idx = element_to_idx[elem]
            conc = np.nan_to_num(
                concentrations[:, i], nan=0.0, posinf=0.0, neginf=0.0
            ).astype(np.float32)
            # Binary presence/absence target expected by BCE loss.
            targets[:, idx] = (conc > threshold).astype(np.float32)
        else:
            print(f"  {elem} -> NOT FOUND!")
    
    print(f"\nTargets: {targets.shape}")
    print(f"  Target value range: [{targets.min():.1f}, {targets.max():.1f}]")
    print(f"  Elements present per sample: {targets.sum(axis=1).mean():.2f} average")
    
    return targets


def train_test_split(X, y, test_size=0.2, random_state=None):
    """Split data into training and test sets."""
    if random_state is not None:
        np.random.seed(random_state)
    n_samples = len(X)
    n_test = int(n_samples * test_size)
    idx = np.random.permutation(n_samples)
    return X[idx[n_test:]], X[idx[:n_test]], y[idx[n_test:]], y[idx[:n_test]]


def normalize_features(X_train, X_test):
    """Normalize features using training set statistics."""
    mean = np.mean(X_train, axis=0)
    std = np.std(X_train, axis=0)
    std[std == 0] = 1
    X_train_norm = np.nan_to_num((X_train - mean) / std, nan=0.0, posinf=0.0, neginf=0.0)
    X_test_norm = np.nan_to_num((X_test - mean) / std, nan=0.0, posinf=0.0, neginf=0.0)
    return X_train_norm, X_test_norm, mean, std


# ============================================================================
# PyTorch Implementation
# ============================================================================

if USE_TORCH:
    class ElementIdentificationNN(nn.Module):
        """
        NN with trainable projection: n_features -> n_elements -> hidden -> n_outputs.
        
        The projection layer reduces 7700 features to 77 (one per element)
        via a learned weight matrix, then feeds into a FC hidden layer.
        """
        
        def __init__(self, n_features, n_elements, n_hidden, n_outputs, dropout=0.2):
            super(ElementIdentificationNN, self).__init__()
            # Learnable projection: (batch, 7700) -> (batch, 77)
            self.projection = nn.Linear(n_features, n_elements, bias=False)
            # FC network on the projected features
            self.network = nn.Sequential(
                nn.Linear(n_elements, n_hidden),
                nn.BatchNorm1d(n_hidden),
                nn.ReLU(),
                nn.Dropout(dropout),
                nn.Linear(n_hidden, n_outputs),
                nn.Sigmoid()
            )
        
        def forward(self, x):
            x = self.projection(x)
            return self.network(x)

    def train_torch(model, train_loader, val_loader, epochs):
        """Train using PyTorch."""
        criterion = nn.BCELoss()
        optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-5)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min', factor=0.5, patience=30)
        
        history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
        best_val_loss = float('inf')
        best_state = None
        
        print(f"\nTraining with PyTorch on {device}...")
        print("-" * 70)
        
        for epoch in range(epochs):
            model.train()
            train_loss, train_correct, train_total = 0.0, 0, 0
            for inputs, targets in train_loader:
                inputs, targets = inputs.to(device), targets.to(device)
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                loss.backward()
                optimizer.step()
                train_loss += loss.item()
                train_correct += ((outputs > 0.5).float() == targets).sum().item()
                train_total += targets.numel()
            
            model.eval()
            val_loss, val_correct, val_total = 0.0, 0, 0
            with torch.no_grad():
                for inputs, targets in val_loader:
                    inputs, targets = inputs.to(device), targets.to(device)
                    outputs = model(inputs)
                    val_loss += criterion(outputs, targets).item()
                    val_correct += ((outputs > 0.5).float() == targets).sum().item()
                    val_total += targets.numel()
            
            train_loss /= len(train_loader)
            val_loss /= len(val_loader)
            train_acc = train_correct / train_total
            val_acc = val_correct / val_total
            
            scheduler.step(val_loss)
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_state = model.state_dict().copy()
            
            history['train_loss'].append(train_loss)
            history['val_loss'].append(val_loss)
            history['train_acc'].append(train_acc)
            history['val_acc'].append(val_acc)
            
            if (epoch + 1) % 100 == 0 or epoch == 0:
                print(f"Epoch {epoch+1:4d}/{epochs}: "
                      f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | "
                      f"Val Loss: {val_loss:.4f}, Acc: {val_acc:.4f}")
        
        if best_state:
            model.load_state_dict(best_state)
        print("-" * 70)
        return history


# ============================================================================
# NumPy Implementation
# ============================================================================

def sigmoid(x):
    x = np.clip(x, -500, 500)
    return np.where(x >= 0, 1 / (1 + np.exp(-x)), np.exp(x) / (1 + np.exp(x)))

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def bce_loss(y_pred, y_true, eps=1e-7):
    y_pred = np.clip(y_pred, eps, 1 - eps)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))


class NumpyNN:
    """
    NN with trainable projection implemented in NumPy.
    
    Architecture: projection (n_features -> n_elements) -> hidden -> output
    The projection layer is a learned weight matrix (no bias).
    """
    
    def __init__(self, n_features, n_elements, n_hidden, n_outputs):
        # Projection layer: (batch, 7700) -> (batch, 77)
        self.W0 = np.random.randn(n_features, n_elements) * np.sqrt(2.0 / n_features)
        # Hidden layer: (batch, 77) -> (batch, n_hidden)
        self.W1 = np.random.randn(n_elements, n_hidden) * np.sqrt(2.0 / n_elements)
        self.b1 = np.zeros((1, n_hidden))
        # Output layer: (batch, n_hidden) -> (batch, n_outputs)
        self.W2 = np.random.randn(n_hidden, n_outputs) * np.sqrt(2.0 / n_hidden)
        self.b2 = np.zeros((1, n_outputs))
        self.cache = {}
    
    def forward(self, X):
        self.cache['X'] = X
        self.cache['P'] = X @ self.W0                       # projection
        self.cache['Z1'] = self.cache['P'] @ self.W1 + self.b1
        self.cache['A1'] = relu(self.cache['Z1'])
        self.cache['Z2'] = self.cache['A1'] @ self.W2 + self.b2
        self.cache['A2'] = sigmoid(self.cache['Z2'])
        return self.cache['A2']
    
    def backward(self, X, y, lr, clip=1.0):
        n = X.shape[0]
        # Output layer gradients
        dZ2 = self.cache['A2'] - y
        dW2 = np.clip(self.cache['A1'].T @ dZ2 / n, -clip, clip)
        db2 = np.clip(np.mean(dZ2, axis=0, keepdims=True), -clip, clip)
        # Hidden layer gradients
        dZ1 = (dZ2 @ self.W2.T) * relu_derivative(self.cache['Z1'])
        dW1 = np.clip(self.cache['P'].T @ dZ1 / n, -clip, clip)
        db1 = np.clip(np.mean(dZ1, axis=0, keepdims=True), -clip, clip)
        # Projection layer gradients
        dP = dZ1 @ self.W1.T
        dW0 = np.clip(self.cache['X'].T @ dP / n, -clip, clip)
        # Update all weights
        self.W2 -= lr * np.nan_to_num(dW2)
        self.b2 -= lr * np.nan_to_num(db2)
        self.W1 -= lr * np.nan_to_num(dW1)
        self.b1 -= lr * np.nan_to_num(db1)
        self.W0 -= lr * np.nan_to_num(dW0)


def train_numpy(model, X_train, y_train, X_val, y_val, epochs, lr):
    """Train using NumPy."""
    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
    print("\nTraining with NumPy...")
    print("-" * 70)
    for epoch in range(epochs):
        train_pred = model.forward(X_train)
        model.backward(X_train, y_train, lr)
        train_loss = bce_loss(train_pred, y_train)
        train_acc = ((train_pred > 0.5) == y_train).mean()
        val_pred = model.forward(X_val)
        val_loss = bce_loss(val_pred, y_val)
        val_acc = ((val_pred > 0.5) == y_val).mean()
        history['train_loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['train_acc'].append(train_acc)
        history['val_acc'].append(val_acc)
        if (epoch + 1) % 100 == 0 or epoch == 0:
            print(f"Epoch {epoch+1:4d}/{epochs}: "
                  f"Train Loss: {train_loss:.4f}, Acc: {train_acc:.4f} | "
                  f"Val Loss: {val_loss:.4f}, Acc: {val_acc:.4f}")
    print("-" * 70)
    return history


# ============================================================================
# Evaluation
# ============================================================================

def evaluate_model(predict_fn, X_test, y_test, element_names):
    """Evaluate model and print results."""
    y_pred = predict_fn(X_test)
    y_pred_binary = (y_pred > 0.5).astype(float)
    
    print("\n" + "=" * 70)
    print("EVALUATION RESULTS")
    print("=" * 70)
    
    overall_acc = (y_pred_binary == y_test).mean()
    print(f"\nOverall Accuracy: {overall_acc:.4f}")
    
    active = np.where(y_test.sum(axis=0) > 0)[0]
    print(f"\nActive elements in test set ({len(active)}):")
    print("-" * 70)
    print(f"{'Element':<10} {'Accuracy':<12} {'Precision':<12} {'Recall':<12} {'F1':<12}")
    print("-" * 70)
    
    for idx in active:
        elem = element_names[idx]
        pred = y_pred_binary[:, idx]
        true = y_test[:, idx]
        acc = (pred == true).mean()
        tp = ((pred == 1) & (true == 1)).sum()
        pp, ap = pred.sum(), true.sum()
        prec = tp / pp if pp > 0 else 0
        rec = tp / ap if ap > 0 else 0
        f1 = 2 * prec * rec / (prec + rec) if (prec + rec) > 0 else 0
        print(f"{elem:<10} {acc:<12.4f} {prec:<12.4f} {rec:<12.4f} {f1:<12.4f}")
    
    print("-" * 70)
    
    print("\nSample Predictions (first 3 test samples):")
    print("-" * 70)
    for i in range(min(3, len(y_test))):
        true_elems = [element_names[j] for j in range(len(element_names)) if y_test[i, j] > 0]
        pred_elems = [element_names[j] for j in range(len(element_names)) if y_pred_binary[i, j] > 0]
        top_idx = np.argsort(y_pred[i])[::-1][:10]
        top_probs = [(element_names[j], y_pred[i, j]) for j in top_idx]
        print(f"\nSample {i+1}:")
        print(f"  True: {true_elems}")
        print(f"  Pred: {pred_elems}")
        print(f"  Top 10: {[(e, f'{p:.3f}') for e, p in top_probs]}")
    
    return y_pred


def print_all_predictions(predict_fn, X_sample, y_true, element_names, sample_idx=0):
    """Print raw NN output probabilities for all elements with ground truth."""
    y_pred = predict_fn(X_sample.reshape(1, -1))[0]
    n = len(element_names)
    
    print("\n" + "=" * 80)
    print(f"ALL {n} ELEMENTS - SAMPLE #{sample_idx + 1}")
    print("=" * 80)
    
    true_elements = [element_names[i] for i in range(n) if y_true[i] > 0.5]
    print(f"\nGround Truth Elements: {true_elements}")
    print(f"Number of elements present: {len(true_elements)}")
    
    sorted_idx = np.argsort(y_pred)[::-1]
    print(f"\n{'Element':<8} {'NN Output':<14} {'Ground Truth':<14}")
    print("-" * 36)
    
    for idx in sorted_idx:
        print(f"{element_names[idx]:<8} {y_pred[idx]:<14.6f} {y_true[idx]:<14.1f}")
    
    print("-" * 36)


# ============================================================================
# Main Execution
# ============================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("Neural Network Training for Element Identification")
    print(f"Backend: {'PyTorch' if USE_TORCH else 'NumPy'}")
    print("=" * 70)
    
    # 1. Load multi-weight spectra (generated by weight_generator.py)
    weight_matrix, unique_elements = load_multi_weights()
    
    # 2. Generate synthetic training data (through DataLoader)
    synth_spectra, concentrations, synth_elements = load_synthetic_data_from_dataloader(batch_size=BATCH_SIZE)
    
    # Check wavelength compatibility
    if synth_spectra.shape[1] != weight_matrix.shape[1]:
        print(f"\nERROR: Wavelength mismatch!")
        print(f"  Synthetic spectra: {synth_spectra.shape[1]} wavelengths")
        print(f"  Weight spectra: {weight_matrix.shape[1]} wavelengths")
        print("Regenerate weights or synthetic data with matching wavelength calibration.")
        sys.exit(1)
    
    # 3. Prepare features via matrix multiplication
    features = prepare_features(synth_spectra, weight_matrix)
    
    # 4. Prepare targets
    targets = prepare_targets(concentrations, synth_elements, unique_elements)
    
    # 5. Split data
    print(f"\nSplitting data (test size: {TEST_SPLIT})...")
    X_train, X_test, y_train, y_test = train_test_split(features, targets, TEST_SPLIT, RANDOM_SEED)
    print(f"  Training: {len(X_train)}, Test: {len(X_test)}")
    
    # 6. Normalize
    print("\nNormalizing features...")
    X_train_norm, X_test_norm, feat_mean, feat_std = normalize_features(X_train, X_test)
    
    n_features = features.shape[1]      # 7700
    n_elements = len(unique_elements)    # 77
    n_outputs = n_elements               # 77
    
    print(f"\nNetwork architecture:")
    print(f"  Features: {n_features} (from weight matrix multiplication)")
    print(f"  Projection: {n_features} -> {n_elements} (trainable weight matrix)")
    print(f"  Hidden: {n_elements} -> {HIDDEN_LAYER_SIZE}")
    print(f"  Output: {HIDDEN_LAYER_SIZE} -> {n_outputs} (0=absent, 1=present)")
    
    # 7. Train
    if USE_TORCH:
        model = ElementIdentificationNN(n_features, n_elements, HIDDEN_LAYER_SIZE, n_outputs).to(device)
        print(f"\nModel:\n{model}")
        
        train_loader = DataLoader(
            TensorDataset(torch.FloatTensor(X_train_norm), torch.FloatTensor(y_train)),
            batch_size=BATCH_SIZE, shuffle=True
        )
        val_loader = DataLoader(
            TensorDataset(torch.FloatTensor(X_test_norm), torch.FloatTensor(y_test)),
            batch_size=BATCH_SIZE
        )
        
        history = train_torch(model, train_loader, val_loader, EPOCHS)
        
        def predict_fn(X):
            model.eval()
            with torch.no_grad():
                return model(torch.FloatTensor(X).to(device)).cpu().numpy()
        
        model_path = os.path.join(SCRIPT_DIR, 'element_identification_model.pt')
        torch.save({
            'model_state_dict': model.state_dict(),
            'feature_mean': feat_mean,
            'feature_std': feat_std,
            'weight_elements': unique_elements,
            'config': {
                'n_features': n_features,
                'n_elements': n_elements,
                'n_hidden': HIDDEN_LAYER_SIZE,
                'n_outputs': n_outputs
            }
        }, model_path)
    else:
        model = NumpyNN(n_features, n_elements, HIDDEN_LAYER_SIZE, n_outputs)
        history = train_numpy(model, X_train_norm, y_train, X_test_norm, y_test, EPOCHS, LEARNING_RATE)
        
        def predict_fn(X):
            return model.forward(X)
        
        model_path = os.path.join(SCRIPT_DIR, 'element_identification_model.pkl')
        with open(model_path, 'wb') as f:
            pickle.dump({
                'W0': model.W0,
                'W1': model.W1, 'b1': model.b1,
                'W2': model.W2, 'b2': model.b2,
                'feature_mean': feat_mean, 'feature_std': feat_std,
                'weight_elements': unique_elements,
                'config': {
                    'n_features': n_features,
                    'n_elements': n_elements,
                    'n_hidden': HIDDEN_LAYER_SIZE,
                    'n_outputs': n_outputs
                }
            }, f)
    
    print(f"\nModel saved to: {model_path}")
    
    # 8. Evaluate
    predictions = evaluate_model(predict_fn, X_test_norm, y_test, unique_elements)
    print_all_predictions(predict_fn, X_test_norm[0], y_test[0], unique_elements, sample_idx=0)
    
    # 9. Summary
    print("\n" + "=" * 70)
    print("TRAINING SUMMARY")
    print("=" * 70)
    print(f"  Weight spectra: {weight_matrix.shape[0]} rows ({weight_matrix.shape[0] // len(unique_elements)} combos x {len(unique_elements)} elements)")
    print(f"  Raw features per sample: {n_features}")
    print(f"  Projected to: {n_elements} (trainable projection layer)")
    print(f"  Final Train Loss: {history['train_loss'][-1]:.4f}")
    print(f"  Final Val Loss: {history['val_loss'][-1]:.4f}")
    print(f"  Final Train Acc: {history['train_acc'][-1]:.4f}")
    print(f"  Final Val Acc: {history['val_acc'][-1]:.4f}")
    print(f"  Output: {n_outputs} elements, each with probability 0-1")
    print("=" * 70)
